### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by rosterloh** [flyinggorilla/esp32gong#1]
Great project! Have you updated your ESP-IDF lately? Build fails on the first file
```
esp32gong/main/./WebServer.cpp:2:23: fatal error: Esp32gong.h: No such file or directory
```

**Comment by flyinggorilla** [comment]
yeah, i hope with the next rainy day i can fix this project. 
please note that this project shares the core components such as webserver, UI, ota update and so forth with this project: https://github.com/Dynatrace/ufo-esp32 
so feel free to tap the ufo-esp32 sources which has the much newer codebase and is also better tested - and compiles. i post an update as soon as i get the esp32gong working again. want to embed also mp3 replay.

**Comment by rosterloh** [comment]
Will do. Thanks!

**Comment by flyinggorilla** [comment]
thanks for the patience. build works again. using the v3 master branch of esp-idf. the biggest todo right now is to add the file-system capabilities
