### ISSUE TITLE
"make" fails with current esp-idf tools (version 4.2)

### ISSUE THREAD

**Issue by happenpappen** [flyinggorilla/esp32gong#3]
the build process fails with:

CXX build/main/I2SPlayer.o
/Users/stoppe/esp32gong/main/I2SPlayer.cpp: In member function 'bool I2SPlayer::play()':
/Users/stoppe/esp32gong/main/I2SPlayer.cpp:80:3: error: 'i2s_push_sample' was not declared in this scope
   i2s_push_sample(I2S_NUM, (char*) &sample_val, portMAX_DELAY);
   ^~~~~~~~~~~~~~~
make[1]: *** [I2SPlayer.o] Error 1
make: *** [component-main-build] Error 2

I checked this and from what i've read i guess this function has gone away in the newer tools versions. Do you know, how to replace it?

**Comment by flyinggorilla** [comment]
Updated to ESP-IDF 4.2 and cleaned-up the project. Works now fine with "idf.py build flash monitor" as well as through Visual Code ESP-IDE plug-in when using Python 3.8 (not 3.9). You may need to run "idf.py erase_flash" when updating existing esp32.

**Comment by flyinggorilla** [comment]
closing.
